services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis_app_net
  app:
    image: 354918395041.dkr.ecr.ap-northeast-2.amazonaws.com/duckwho:latest
    platform: linux/amd64
    ports:
      - "8081:8080" # 호스트 포트를 8081로 변경
    depends_on:
      - redis
    networks:
      - redis_app_net
networks:
  redis_app_net:
    driver: bridge