services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis_app_net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 354918395041.dkr.ecr.ap-northeast-2.amazonaws.com/duckwho:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - redis_app_net
networks:
  redis_app_net:
    driver: bridge